name: Hugo build

on:
  push:
    branches:
      - main
      - hugo-test
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: yarn && hugo -b https://eclipse-opensmartclide.github.io/opensmartclide-website/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO_TOKEN }}
          external_repository: eclipse-opensmartclide/opensmartclide-website
          publish_branch: gh-pages  # default: gh-pages  
          #publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: Website build. Run number ${{github.run_number}} 
